#!/usr/bin/env bash
# Configure your domain zone
display_info() {
    local subdomain="$1"
    local domain="$2"
    dig_output=$(dig +short "$subdomain.$domain")

    if [ -n "$dig_output" ]; then
	record_type=$(echo "$dig_output" | awk 'NR==1{print $4}')
	destination=$(echo "$dig_output" | awk 'NR==2{print $1}')
	echo "The subdomain $subdomain is a $record_type record and points to $destination"
    else
	echo "The subdomain $subdomain does not exist."
    fi
}

if [ "$#" -eq 2 ]; then
    display_info "$2" "$1"
elif [ "$#" -eq 1 ]; then
    display_info "www" "$1"
    display_info "lb-01" "$1"
    display_info "web-01" "$1"
    display_info "web-02" "$1"
else
    exit 1
fi
