#!/usr/bin/env bash
# Configure your domain zone
display_info() {
    local domain="$1"
    local subdomain="$2"
    local dns_info=$(dig +short "${subdomain}.${domain}")

    if [ -n "$dns_info" ]; then
	echo "The subdomain ${subdomain} is a A record and points to ${dns_info}"
    else
        echo "No DNS information found for subdomain ${subdomain}"
    fi
}

main() {
    local domain="$1"
    local subdomain="$2"

    if [ -z "$subdomain" ]; then
        subdomain="www lb-01 web-01 web-02"
    fi

    for sub in $subdomain; do
        display_info "$domain" "$sub"
    done
}

main "$1" "$2"
