#!/bin/env bash
# script that transfers a file from our client to a server
if [ "$#" -ne 3 ]; then
	echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi;

if ["$#" -ge 4]; then
	scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2:~/"
else
	scp -o StrictHostKeyChecking=no "$1" "$3@$2:~/"
fi
