#!/bin/bash
# Nginx server Redirection
sudo apt-get update -y
sudo apt-get install nginx -y
sudo sed -i '/server_name _;/a \\nlocation /redirect_me {\n    return 301 https://xtechsoftwarelib.com;\n}' /etc/nginx/sites-available/default
sudo service nginx restart
