#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page
sudo apt-get update -y
sudo apt-get install nginx -y
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html > /dev/null
sudo sed -i '/server_name _;/a \\nerror_page 404 /custom_404.html;\nlocation = /custom_404.html {\n    root /var/www/html;\n    internal;\n}' /etc/nginx/sites-available/default
sudo service nginx restart
