#!/usr/bin/env bash
# Install nginx on web-02
sudo apt-get update -y
sudo apt-get install nginx -y
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html > /dev/null
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
redirect_url="https://xtechsoftwarelib.com"
config_file="/etc/nginx/sites-available/default"
sudo sed -i '/server_name _;/a \\nlocation /redirect_me {\n    return 301 '"$redirect_url"';\n}' "$config_file"
custom_header_config="add_header X-Served-By \$HOSTNAME;"
sudo sed -i '/server_name _;/a '"$custom_header_config" "$config_file"
sudo sed -i '/server_name _;/a \\nerror_page 404 /custom_404.html;\nlocation = /custom_404.html {\n    root /var/www/html;\n    internal;\n}' "$config_file"
sudo service nginx start
