#!/usr/bin/env bash
# Bash script that displays To infinity and beyond indefinitely
trap 'echo "Y U no love me?!"' SIGINT
trap 'echo "I hate the kill command"; rm -f "/var/run/myscript.pid"; exit' SIGTERM

echo "$$" > "/var/run/myscript.pid"
while true
do
	echo "To infinity and beyond"
	sleep 2
done
