#!/usr/bin/env bash
# Bash script displays content file /etc/passwd, using while loop + IFS.
while IFS=':' read -r username _ userid groupid password _ info homedir shell; do
    echo "The user $username is part of the gang $groupid, lives in $homedir, and rides $shell."\
	    "$userid's place is protected by the passcode $password, more info about the user here: $info"
done < "/etc/passwd"
