#!/usr/bin/env bash
# script to make Nginx run as nginx user
sudo service nginx stop
sudo killall nginx
sudo chown -R nginx:nginx /var/log/nginx
sudo chown -R nginx:nginx /var/lib/nginx
sudo chown -R nginx:nginx /etc/nginx
sudo rm /run/nginx.pid
sudo chmod 755 /run
sudo touch /run/nginx.pid
sudo chown nginx:nginx /run/nginx.pid
sudo sed -i 's/user\s*.*;/user nginx;/' /etc/nginx/nginx.conf
sudo sed -i '/listen\s*.*;/d' /etc/nginx/sites-available/default
sudo sed -i '/server {/a \    listen 8080 default_server;' /etc/nginx/sites-available/default
sudo service nginx start
