#!/usr/bin/env bash
# script to make Nginx run as nginx user

if pgrep "apache2" > /dev/null; then
    sudo pkill apache2
fi

sudo chown -R nginx:nginx /etc/nginx
sudo chmod -R 644 /etc/nginx
sudo chmod -R 777 /etc/nginx/
sudo service nginx stop
sudo sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo -u nginx service nginx start
