#!/usr/bin/env bash
# script to make Nginx run as nginx user
sudo pkill apache2
sudo chmod -R 777 /etc/nginx/
sudo service nginx stop
sudo sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo -u nginx service nginx start
